RootTable.exe : RootTable.o myLinkedList.o
	gcc -o RootTable.exe RootTable.o myLinkedList.o

myLinkedList.o : myLinkedList.c myLinkedList.h
	gcc -c myLinkedList.c

RootTable.o : RootTable.c 
	gcc -c RootTable.c
